# Generated by Django 3.1.1 on 2021-10-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_uid', models.UUIDField(unique=True)),
                ('content', models.CharField(max_length=1024)),
                ('equipment_model_uid', models.UUIDField(unique=True)),
            ],
        ),
    ]
