# Generated by Django 3.1.1 on 2021-10-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.UUIDField(unique=True)),
                ('login', models.CharField(max_length=31, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
                ('current_token', models.CharField(max_length=255)),
            ],
        ),
    ]
