# Generated by Django 3.2.5 on 2021-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_uid', models.UUIDField(unique=True)),
                ('brand', models.CharField(max_length=31)),
                ('model', models.CharField(max_length=31)),
                ('power', models.CharField(max_length=31)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
