# Generated by Django 3.1.1 on 2021-10-13 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('monitor_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('equipment_uid', models.CharField(max_length=256)),
                ('equipment_models_uid', models.CharField(max_length=256)),
            ],
        ),
    ]
